# Data understanding

The purpose of this notebook is to explore the raw dataset before designing the ETL pipeline.

The main objectives are:

- Explore the structure and quality of the dataset.
- Identify missing values, duplicates, and potential data issues.

In [16]:
import pandas as pd

In [17]:
df = pd.read_csv("../data/restaurant_inventory_100days.csv")

## First look at the dataset

In [18]:
df.head()

,Date,Item_ID,Item_Name,Category,Subcategory,Unit,Current_Stock,Reorder_Level,Daily_Usage,Lead_Time,Price_per_Unit,Supplier_Name,Seasonal_Factor,Waste_Percentage
0,2025-06-10,1,Paneer,Veg,Dairy,kg,21.45,8.12,2.19,1,450,Supplier A,1.11,2.98
1,2025-06-10,2,Tomato,Veg,Vegetable,kg,12.84,5.34,0.95,4,40,Supplier A,0.81,3.54
2,2025-06-10,3,Onion,Veg,Vegetable,kg,22.35,4.49,4.86,4,35,Supplier A,1.23,4.96
3,2025-06-10,4,Chicken,Non-Veg,Meat,kg,8.36,3.16,3.25,3,250,Supplier C,0.90,3.06
4,2025-06-10,5,Mutton,Non-Veg,Meat,kg,12.31,6.19,1.81,3,600,Supplier A,1.07,3.09

In [19]:
df.tail()

,Date,Item_ID,Item_Name,Category,Subcategory,Unit,Current_Stock,Reorder_Level,Daily_Usage,Lead_Time,Price_per_Unit,Supplier_Name,Seasonal_Factor,Waste_Percentage
995,2025-09-17,6,Rohu Fish,Non-Veg,Fish,kg,10.34,3.48,3.55,1,280,Supplier B,1.23,1.74
996,2025-09-17,7,Eggs,Non-Veg,Poultry,pieces,26.17,3.63,8.00,4,6,Supplier B,0.95,1.19
997,2025-09-17,8,Rice,Veg,Grain,kg,17.91,4.52,2.35,3,70,Supplier C,1.41,0.70
998,2025-09-17,9,Sugar,Veg,Grocery,kg,15.70,6.11,4.42,1,50,Supplier A,1.02,0.34
999,2025-09-17,10,Milk,Veg,Dairy,liter,20.59,8.44,8.00,4,50,Supplier C,0.81,3.73

## Dataset overview

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date              1000 non-null   str
 1   Item_ID           1000 non-null   int64
 2   Item_Name         1000 non-null   str
 3   Category          1000 non-null   str
 4   Subcategory       1000 non-null   str
 5   Unit              1000 non-null   str
 6   Current_Stock     1000 non-null   float64
 7   Reorder_Level     1000 non-null   float64
 8   Daily_Usage       1000 non-null   float64
 9   Lead_Time         1000 non-null   int64
 10  Price_per_Unit    1000 non-null   int64
 11  Supplier_Name     1000 non-null   str
 12  Seasonal_Factor   1000 non-null   float64
 13  Waste_Percentage  1000 non-null   float64
dtypes: float64(5), int64(3), str(6)
memory usage: 109.5 KB

The dataset contains 1,000 records and 14 columns. No missing values are visible in the dataset structure. The Date column is currently stored as a string and will require conversion during the transformation stage.

In [21]:
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

Rows: 1000
Columns: 14

In [22]:
df.columns.tolist()

['Date',
 'Item_ID',
 'Item_Name',
 'Category',
 'Subcategory',
 'Unit',
 'Current_Stock',
 'Reorder_Level',
 'Daily_Usage',
 'Lead_Time',
 'Price_per_Unit',
 'Supplier_Name',
 'Seasonal_Factor',
 'Waste_Percentage']

## Description of the columns

Date: The specific date of the inventory record.

Item_ID: A unique identifier for each menu item.

Item_Name: The name of the inventory item (e.g., 'Paneer', 'Chicken', 'Rice').

Category: The primary food group (e.g., 'Veg', 'Non-Veg').

Subcategory: A more specific classification of the item (e.g., 'Dairy', 'Meat', 'Vegetable').

Unit: The unit of measurement for the item (e.g., 'kg', 'pieces').

Current_Stock: The quantity of the item currently in stock.

Reorder_Level: The stock level at which a new order should be placed.

Daily_Usage: The average daily consumption of the item.

Lead_Time: The number of days it takes for a new order to arrive after being placed.

Price_per_Unit: The cost of a single unit of the item.

Supplier_Name: The name of the supplier for the item.

Seasonal_Factor: A multiplier indicating how seasonality affects demand. A value greater than 1 suggests higher demand, while a value less than 1 suggests lower demand.

Waste_Percentage: The percentage of the item that is typically wasted.

Although info() confirms that the dataset is complete, this can also be verified using the following method.

In [23]:
df.isna().sum()

Date                0
Item_ID             0
Item_Name           0
Category            0
Subcategory         0
Unit                0
Current_Stock       0
Reorder_Level       0
Daily_Usage         0
Lead_Time           0
Price_per_Unit      0
Supplier_Name       0
Seasonal_Factor     0
Waste_Percentage    0
dtype: int64

## Duplicate records

In [24]:
df.duplicated().sum()

np.int64(0)

No duplicate records were found in the dataset.

## Data Coverage

The dataset is examined to identify the first and last available dates and the overall period covered by the data.

In [25]:
df["Date"] = pd.to_datetime(df["Date"])

In [26]:
df["Date"].describe()

count                   1000
mean     2025-07-29 12:00:00
min      2025-06-10 00:00:00
25%      2025-07-04 18:00:00
50%      2025-07-29 12:00:00
75%      2025-08-23 06:00:00
max      2025-09-17 00:00:00
Name: Date, dtype: object

The dataset covers the period from June 10, 2025, to September 17, 2025, representing approximately 100 days of inventory records.

## Records per day

To verify the structure of the dataset, I checked how many
records are available for each date.

In [27]:
df.groupby("Date").size().describe()

count    100.0
mean      10.0
std        0.0
min       10.0
25%       10.0
50%       10.0
75%       10.0
max       10.0
dtype: float64

In [28]:
df["Date"].nunique()

100

In [29]:
df.groupby("Date")["Item_ID"].nunique().describe()

count    100.0
mean      10.0
std        0.0
min       10.0
25%       10.0
50%       10.0
75%       10.0
max       10.0
Name: Item_ID, dtype: float64

In [30]:
df.groupby("Item_ID")["Date"].nunique().describe()

count     10.0
mean     100.0
std        0.0
min      100.0
25%      100.0
50%      100.0
75%      100.0
max      100.0
Name: Date, dtype: float64

## Findings

The dataset contains 100 unique dates and exactly 10 records
for each date.

This results in 1,000 records in total:

- 100 days
- 10 records per day
- 1,000 total records

The number of records per day is constant, with a standard
deviation of 0.

This suggests that the dataset has a regular daily structure,
where the same number of inventory items is recorded each day.

### Summary

The dataset is in good condition for exploratory analysis.

Key observations:

- No missing values were detected.
- No duplicate records were found.
- Data types are appropriate after converting the **Date** column.